public class UTIL_Constants {
	public static final String LOAN_TYPE 				= 'Home Loan';
    public static final String MDT_CONFIG_MAILGUNAPI 	= 'Mailgun_API';
    public static final String MDT_CONFIG_WELCOMEEMAIL 	= 'Home_Loan_Welcome_Email';
    public static final String SUCCESS_WELCOMEEMAIL 	= 'Welcome email sent successfully';
    public static final String ERROR_WELCOMEEMAIL		= 'Error: Welcome email not sent';
    public static final String ERROR_CONTACTUNAVAILABLE	= 'Contact records not present. Create contact and send welcome email again.';
    public static final String ERROR_EMAILIDUNAVAILABLE	= 'Email id is not available. Enter email id in Contact record and send welcome email again.';
    public static final String ERROR_CLASSEXCEPTION	    = 'Please contact salesforce administrator. Error Message: ';
}